project_id = "vxtapurbpcgzgntqewol"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.call-status-webhook]
verify_jwt = false

[functions.twilio-media-stream]
verify_jwt = false

